<?php include("../../includes/header.php"); ?>
	<title  dir=ltr>Mobile First? Do it. Do it now. by Jefff</title>
<?php include("../../includes/content.php"); ?>
		<article class="full">
			<h2 class="header">january 24, 2012 <span>web</span></h2>
			<h1>Mobile First? Do it. Do it now.</h1>
			<p><strong><img src="http://jhische.com/dailydropcap/W-1-cap.png" title="Daily Drop Cap by Jessica Hische" alt="W" id="drop-cap" /><del>W</del>hat&rsquo;s All the Hubbub About Mobile First Mobileness??</strong> While it is a hot new term, It&rsquo;s not just a hot new term. It&rsquo;s much, much more than that. It&rsquo;s a whole new way of thinking about users, content, web design, and the lot. Do a <a href="https://www.google.com/search?q=mobile+first" target="_blank">Google search for &rsquo;mobile first&rsquo;</a> and you&rsquo;ll find somewhere in the neighborhood of 4,520,000,000 results. That&rsquo;s a lot of results.</p>
			<img src="/images/Responsive-Web-Design.jpeg" alt="An example of a semi-mobile-first approach to the web." />
			<figcaption>This image shows how http://www.davidhughes.org/ used to be designed, responsively. Although it looks different now, the site is still responsive. <em><a href="http://www.reliablenetworks.co.uk/Blog/wp-content/uploads/2011/12/Responsive-Web-Design.jpg" target="_blank">Lovely image citation</a></em></figcaption>
			<h2>Okay, so, there&rsquo;s a lot of content about it&mdash;so what?</h2>
			<p>How does this affect everyday website owners? Isn&rsquo;t this just another aspect of the web that only the early adopters really need to know about? Unfortunately/fortunately no. Mobile is here, and has been here for a while now, so it&rsquo;s time to start thinking about it, and to start planning for this from the beginning. The mobile first concept is basically a web strategy that puts users on mobile devices as your first priority and then you work your way outward to desktop users. This is not to imply or say that desktop users are any less important than mobile users, certainly not. These users still account for most web traffic. However, up until now, most mobile users have been given a mobile second (or worse mobile shmobile) view, and have had to deal with subpar content delivery on their devices.</p>
			<h2>Sure it sounds great, but I can&rsquo;t afford mobile magic</h2>
			<p>Tut tut tut, yes you can. And yes you really kind of have to. With the vigor and speed of technology moving more and users to mobile (not necessarily away from desktop altogether, but in addition), this is something that in 2012 has to become just part of our thinking and attitude. Kudos to those who&rsquo;ve already seen the light, and done something about it. There are a few different ways to approach this and to make it work well. One: create a separate iteration of your entire site with mobile needs at the forefront and planning for what is needed and what is not, and Two: create a mobile site that has just what your users need most while on their devices. This isn&rsquo;t a really one or the other, as with everything on the web, it&rsquo;s all relative.</p>
			<p><em>Relative to your users, relative to your content, and relative to your budget.</em> Relative to your users in that some companies have users that are early adopters and will push the technology barrier often, whereas others have users who probably don&rsquo;t user their mobile device for much other than getting contact info. The same goes for the type of content. If you have a website with thousands of pages of good textual content, then you&rsquo;ll probably want a fuller mobile experience; but if you&rsquo;re site is more of just a brochure site, then a few mobile optimized pages will most likely do the trick. Obviously, cost plays a factor here as well, so your budget is another thing to consider. Fortunately for us, technology is on our side here.</p>
			</article>
			<article class="full">
			<p>There are a few different ways to optimize a site for mobile experience: true mobile templates and using responsive web techniques. The first is pretty self-explanatory, where a designer or developer would create templates built for mobile and that only include what is truly needed for the mobile experience. Mobile browsers can render most of the content on a website these days (with the exception of iOS devices and Flash of course), but due to dramatic differences in user expectations and processor speeds on a mobile device, we really don&rsquo;t want to force users to get the same content as desktop users. So, by removing all extraneous content (part IA, part design, and part development), we can really make a mobile experience simple, easy and at times, fun.</p>
			<p>The second technique is based on the same principles as the first, optimizing for mobile views, but it goes about this in a different way. What using responsive web techniques (combining CSS Media Queries and some JavaScript) does is it reformats the layout to fit into most mobile devices. While this seems like a no-brainer, and that everyone should do this, the main problem with this is that the non-mobile content is just hidden from the device, not truly taken out of the equation. <strong>So what that means is the page load time is not truly optimized for mobile, and as anyone who&rsquo;s ever used a mobile device knows, page load time REALLY matters.</strong> However, devices are getting faster all the time, as are networks, so eventually this may not truly matter.</p>
			<small><em>Note: there are some very advanced techniques <sup>1</sup> that can be applied to help responsive design out a bit as well, however for this instance I&rsquo;m just assuming normal CSS/JS methods are being used.</em></small>
			<h2>Okay, now I know why, but when to do this?</h2>
			<p>As the concept implies, mobile first means mobile first. When you and a designer/firm first talk about an upcoming project, talk about it then. Before you start working on the IA, talk about it then. Before the design begins, talk about it then. Before you begin writing the content, talk about it then.</h2>
			<p>What this really boils down to is that thinking with mobile in mind first helps you to think about what&rsquo;s absolutely most important to your users. Are they really going to care about that press release? Is that stock photo really going to woo them? What about those ads you on your desktop site, are they really relevant to mobile users? If/when you visit a site on a mobile device, what are you impressed with? Conversely, what annoys you the most? Thinking about things this way, really helps you predict what the best user experience you want to offer to your mobile users is going to be.</p>
			<h2>No silver bullet</h2>
			<p>This is not a perfect solution&mdash;nothing ever is. <strong>If you spend hours and hours crafting the best mobile experience, but neglect the content and/or the design, then it&rsquo;s kind of all for naught.</strong></p>
			<p>People are still going to dislike this or that on your site, that&rsquo;s just a fact of human nature. But approaching it this way, with their overall best interests in mind is going to do wonders for making their experience more enjoyable, and their perception of your company more favorable. Remember, it&rsquo;s the little things in life that count.</p>
			<h2>Some resources:</h2>
			<ul>
				<li><a href="http://www.lukew.com/ff/entry.asp?933" target="_blank">basically anything</a> <a href="http://www.abookapart.com/products/mobile-first" target="_blank">by Luke W</a></li>
				<li><a href="http://www.slideshare.net/bryanrieger/rethinking-the-mobile-web-by-yiibu" target="_blank">Rethinking the Mobile Web by Yiibu</a></li>
				<li><a href="http://speakerdeck.com/u/grigs/p/choose-your-mobile-adventure-webvisions-nyc" target="_blank">Choose Your Mobile Adventure &ndash; WebVisions NYC</a></li>
				<li><a href="https://www.google.com/search?aq=f&sourceid=chrome&ie=UTF-8&q=content+strategy" target="_blank">In addition to Mobile First, you should jive Content Strategy</a></li>
				<li><a href="https://www.google.com/search?q=boston+globe+responsive+design" target="_blank">How the Boston Globe went responsive all over America <sup>1</sup></a></li>
			</ul>
			<hr />
			<a href="../whats-cta-to-you/" id="prev" class="more"><span aria-hidden="true" data-icon="A"></span> Previous</a>
			<a href="../new-face-of-web-typography/" id="next" class="more"><span aria-hidden="true" data-icon="A"></span> Next</a>
		</article>
<?php include("../../includes/footer.php"); ?>